export const PATH = {
  MAIN: "/",
  WELCOME: "/welcome",
  WELCOMETERM: "/welcome/term",
  WELCOMETERMDETAIL: "/welcome/term/detail",
  COURSES: "/courses",
  CATEGORY1: "/courses/0",
  CATEGORY2: "/courses/1",
  CATEGORY3: "/courses/2",
  CATEGORY4: "/courses/3",
  COURSESDETAIL: "/courses/detail",
  COURSESSUCCESS: "/courses/success",
  SEARCH: "/search",
  PRACTICE: "/practice",
  PRACTICEDETAIL: "/practice/detail",
  PRACTICESUCCESS: "/practice/success",
  CHATBOT: "/chatbot",
  CHATBOTDETAIL: "/chatbot/detail",
  ACCOUNT: "/account",
};
