export const TEXT = {
  HEADLINE: {
    FONTFAMILY: "Pretendard",
    SIZE: "2.00rem",
    HEIGHT: "3.00rem",
    WEIGTHT: 700,
    LETTER_SPACING: "-0.01rem",
  },
  TITLE1: {
    FONTFAMILY: "Pretendard",
    SIZE: "1.375rem",
    HEIGHT: "2.25rem",
    WEIGTHT: 700,
    LETTER_SPACING: "-0.01rem",
  },
  TITLE2: {
    FONTFAMILY: "Pretendard",
    SIZE: "1.25rem",
    HEIGHT: "2.00rem",
    WEIGTHT: 700,
    LETTER_SPACING: "-0.01rem",
  },
  SUBTITLE1: {
    FONTFAMILY: "Pretendard",
    SIZE: "1.25rem",
    HEIGHT: "2.00rem",
    WEIGTHT: 500,
    LETTER_SPACING: "-0.01rem",
  },
  SUBTITLE2: {
    FONTFAMILY: "Pretendard",
    SIZE: "1.125rem",
    HEIGHT: "2.00rem",
    WEIGTHT: 500,
    LETTER_SPACING: "-0.01rem",
  },
  BODY1: {
    FONTFAMILY: "Pretendard",
    SIZE: "1.00rem",
    HEIGHT: "1.75rem",
    WEIGTHT: 700,
    LETTER_SPACING: "-0.01rem",
  },
  BODY2: {
    FONTFAMILY: "Pretendard",
    SIZE: "1.00rem",
    HEIGHT: "1.75rem",
    WEIGTHT: 500,
    LETTER_SPACING: "-0.01rem",
  },
  BODY3: {
    FONTFAMILY: "Pretendard",
    SIZE: "1.00rem",
    HEIGHT: "1.75rem",
    WEIGTHT: 400,
    LETTER_SPACING: "-0.01rem",
  },
  CAPTION1: {
    FONTFAMILY: "Pretendard",
    SIZE: "0.875rem",
    HEIGHT: "1.3125rem",
    WEIGTHT: 500,
    LETTER_SPACING: "-0.01rem",
  },
  CAPTION2: {
    FONTFAMILY: "Pretendard",
    SIZE: "0.75rem",
    HEIGHT: "1.125rem",
    WEIGTHT: 500,
    LETTER_SPACING: "-0.01rem",
  },
  SPECIALTITLE1: {
    FONTFAMILY: "Poppins",
    SIZE: "2.5rem",
    HEIGHT: "3.5rem",
    WEIGTHT: 700,
    LETTER_SPACING: "+0.05rem",
  },
  SPECIALTITLE2: {
    FONTFAMILY: "Poppins",
    SIZE: "2.00rem",
    HEIGHT: "3.00rem",
    WEIGTHT: 500,
    LETTER_SPACING: "+0.05rem",
  },
  SPECIALSUBTITLE1: {
    FONTFAMILY: "Poppins",
    SIZE: "1.5rem",
    HEIGHT: "2.25rem",
    WEIGTHT: 700,
    LETTER_SPACING: "+0.05rem",
  },
  SPECIALSUBTITLE2: {
    FONTFAMILY: "Poppins",
    SIZE: "1.25rem",
    HEIGHT: "2.00rem",
    WEIGTHT: 500,
    LETTER_SPACING: "+0.05rem",
  },
};
